Repository balena-io/docs, pull requests merged in 2018-05, with the labels that each got.

#794 Update information on API keys
  CHANGELOG.md
  package.json
  pages/learn/manage/account.md
  pages/reference/data-api.md
  static/img/common/preferences/access_tokens.png
  static/img/common/preferences/api_key_delete.png
  static/img/common/preferences/api_key_list.png
  static/img/common/preferences/api_key_name.png
  static/img/common/preferences/api_key_warning.png
  static/img/common/preferences/create_api_key.png
  static/img/common/preferences/preferences_2_factor_enable.png
  static/img/common/preferences/preferences_account_details.png
  static/img/common/preferences/preferences_account_details_cropped.png
  static/img/common/preferences/preferences_ssh_keys.png
  static/img/common/preferences/preferences_ssh_keys_edit.png
Labels: in progress, procbots/versionbot/ready-to-merge

#795 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/manage/account.md
  pages/reference/data-api.md
  static/img/common/preferences/access_tokens.png
  static/img/common/preferences/api_key_delete.png
  static/img/common/preferences/api_key_list.png
  static/img/common/preferences/api_key_name.png
  static/img/common/preferences/api_key_warning.png
  static/img/common/preferences/create_api_key.png
  static/img/common/preferences/preferences_2_factor_enable.png
  static/img/common/preferences/preferences_account_details.png
  static/img/common/preferences/preferences_account_details_cropped.png
  static/img/common/preferences/preferences_ssh_keys.png
  static/img/common/preferences/preferences_ssh_keys_edit.png
Labels: procbots/versionbot/no-checks

#798 Improve and update API documentation
  CHANGELOG.md
  config/dictionaries/resource.json
  config/links.coffee
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/reference/api/overview.md
  pages/reference/api/resources.md
  shared/apiGeneral/auth.md
  shared/apiGeneral/calls.md
  shared/apiGeneral/introduction.md
  shared/apiGeneral/versioning.md
  templates/api.html
Labels: in progress, procbots/versionbot/ready-to-merge

#806 Deploy to production
  CHANGELOG.md
  README.md
  config/dictionaries/resource.json
  config/links.coffee
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/faq/troubleshooting/troubleshooting.md
  pages/reference/api/overview.md
  pages/reference/api/resources.md
  shared/apiGeneral/auth.md
  shared/apiGeneral/calls.md
  shared/apiGeneral/introduction.md
  shared/apiGeneral/versioning.md
  shared/getDeviceOnDash/raspberry-pi.md
  shared/getDeviceOnDash/raspberry-pi2.md
  shared/getDeviceOnDash/raspberrypi3.md
  shared/usingSupport/_default.md
  templates/api.html
Labels: in progress, procbots/versionbot/no-checks

#811 add latest device types which can be self-service updated
  CHANGELOG.md
  package.json
  pages/reference/resinOS/updates/self-service.md
Labels: in progress, procbots/versionbot/ready-to-merge

#815 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/more/examples/seed-projects.md
  pages/reference/resinOS/updates/self-service.md
Labels: in progress, procbots/versionbot/no-checks

#817 Add balena socket label to list of labels
  CHANGELOG.md
  package.json
  shared/general/labels.md
Labels: in progress, procbots/versionbot/ready-to-merge

#818 Deploy to production
  CHANGELOG.md
  package.json
  shared/general/labels.md
Labels: in progress, procbots/versionbot/no-checks
