Repository balena-io/docs, pull requests merged in 2018-02, with the labels that each got.

#707 Updating resinOS: adding newly supported devices to the documentation
  CHANGELOG.md
  package.json
  pages/updates/self-service.md
Labels: procbots/versionbot/ready-to-merge

#710 Update delta info
  CHANGELOG.md
  package.json
  pages/runtime/delta.md
Labels: in progress, procbots/versionbot/ready-to-merge

#716 Update docs on hostOS update process
  CHANGELOG.md
  package.json
  pages/updates/self-service.md
  pages/updates/update-process.md
Labels: in progress, procbots/versionbot/ready-to-merge

#717 Deploy to production
  CHANGELOG.md
  package.json
  pages/runtime/delta.md
  pages/runtime/resin-base-images.md
  pages/updates/self-service.md
  pages/updates/update-process.md
Labels: in progress, procbots/versionbot/no-checks

#711 Include warning about using git repo as code hosting
  CHANGELOG.md
  package.json
  pages/deployment/deployment.md
  pages/understanding/understanding-code-deployment.md
  shared/deployingCode/cpp.md
  shared/deployingCode/go.md
  shared/deployingCode/nodejs.md
  shared/deployingCode/python.md
  shared/deployingCode/rust.md
Labels: in progress, procbots/versionbot/ready-to-merge

#718 Fix the improve this doc button on dynamic pages
  CHANGELOG.md
  config/doxx.coffee
  config/index.coffee
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/getting-started.md
Labels: in progress, procbots/versionbot/ready-to-merge

#719 Deploy to production
  CHANGELOG.md
  config/doxx.coffee
  config/index.coffee
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/deployment/deployment.md
  pages/getting-started.md
  pages/understanding/understanding-code-deployment.md
  shared/deployingCode/cpp.md
  shared/deployingCode/go.md
  shared/deployingCode/nodejs.md
  shared/deployingCode/python.md
  shared/deployingCode/rust.md
Labels: in progress, procbots/versionbot/no-checks

#712 Update version name conventions
  CHANGELOG.md
  package.json
  shared/insideResinOS/2.x.md
Labels: in progress, procbots/versionbot/ready-to-merge

#709 Included instructions for terminal copy/paste
  CHANGELOG.md
  package.json
  shared/general/container-ssh.md
Labels: in progress, procbots/versionbot/ready-to-merge

#703 Put all getting started guides into parametric format
  CHANGELOG.md
  config/dictionaries/device.json
  config/redirects.txt
  package.json
  pages/getting-started.md
  pages/hardware/devices.md
  shared/flashingOsToBootMedia/intel-edison.md
  shared/getDeviceOnDash/intel-edison.md
  shared/getDeviceOnDash/odroid-c1.md
  shared/getDeviceOnDash/odroid-xu4.md
  shared/getDeviceOnDash/ts4900.md
  shared/whatYouNeed/intel-edison.md
  shared/whatYouNeed/odroid-c1.md
  shared/whatYouNeed/odroid-xu4.md
  shared/whatYouNeed/ts4900.md
  static/img/edison.jpg
  templates/getting-started.html
Labels: in progress, procbots/versionbot/ready-to-merge

#708 Add tag name restrictions
  CHANGELOG.md
  package.json
  pages/management/applications.md
Labels: in progress, procbots/versionbot/ready-to-merge

#727 Update circleci configuration
  .circleci/config.yml
  CHANGELOG.md
  circle.yml
  package.json
Labels: in progress, procbots/versionbot/ready-to-merge
