Repository balena-io/docs, pull requests merged in 2018-04, with the labels that each got.

#772 Updates for device (environment) variables
  CHANGELOG.md
  package.json
  pages/learn/manage/serv-vars.md
  static/img/env-vars/add_application_variable.png
Labels: in progress, procbots/versionbot/ready-to-merge

#776 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/manage/serv-vars.md
  static/img/env-vars/add_application_variable.png
Labels: in progress, procbots/versionbot/no-checks

#779 Add a note about python-networkmanager installation
  CHANGELOG.md
  package.json
  shared/networking/2.x.md
Labels: in progress, procbots/versionbot/ready-to-merge

#781 Deploy to production
  CHANGELOG.md
  package.json
  pages/reference/resinOS/updates/self-service.md
  shared/networking/2.x.md
Labels: in progress, procbots/versionbot/no-checks

#783 Update TX2 flashing instructions
  CHANGELOG.md
  package.json
  shared/getDeviceOnDash/jetson-tx2.md
Labels: in progress, procbots/versionbot/ready-to-merge

#784 Added getting started for Haskell
  CHANGELOG.md
  config/dictionaries/language.json
  package.json
  shared/deployingCode/haskell.md
  static/img/common/pushing/success_unicorn_resin_haskell_hello_world.png
  static/img/language/haskell.svg
Labels: in progress, procbots/versionbot/ready-to-merge

#786 Deploy to production
  CHANGELOG.md
  config/dictionaries/language.json
  package.json
  shared/deployingCode/haskell.md
  shared/getDeviceOnDash/jetson-tx2.md
  static/img/common/pushing/success_unicorn_resin_haskell_hello_world.png
  static/img/language/haskell.svg
Labels: procbots/versionbot/no-checks

#787 Add Samsung ARTIK 710 to the self-service resinHUP supported list
  CHANGELOG.md
  package.json
  pages/reference/resinOS/updates/self-service.md
Labels: in progress, procbots/versionbot/ready-to-merge

#788 Updates for supported devices
  CHANGELOG.md
  package.json
  shared/general/resinDeviceTypeNames.md
  static/scripts/main.js
Labels: in progress, procbots/versionbot/ready-to-merge

#789 Deploy to production
  CHANGELOG.md
  package.json
  pages/reference/resinOS/updates/self-service.md
  shared/general/resinDeviceTypeNames.md
  static/scripts/main.js
Labels: in progress, procbots/versionbot/no-checks

#792 Add info for new supported devices.
  CHANGELOG.md
  package.json
  pages/reference/base-images/resin-base-images.md
Labels: in progress, procbots/versionbot/ready-to-merge

#793 Deploy to production
  CHANGELOG.md
  package.json
  pages/reference/base-images/resin-base-images.md
Labels: procbots/versionbot/no-checks
