Repository balena-io/docs, pull requests merged in 2018-08, with the labels that each got.

#860 Add section on group OS updates
  CHANGELOG.md
  package.json
  pages/reference/OS/updates/self-service.md
  static/img/common/updates/group-update.png
Labels: in progress, procbots/versionbot/ready-to-merge

#861 Deploy to production
  CHANGELOG.md
  config/navigation.txt
  package.json
  pages/reference/OS/updates/self-service.md
  static/img/common/updates/group-update.png
Labels: in progress, procbots/versionbot/no-checks

#871 fix: Update supported Artik boards
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/reference/base-images/base-images.md
  shared/general/deviceTypeNames.md
  shared/getting-started/exampleProjects/artik5+nodejs.md
  shared/getting-started/exampleProjects/artik5+python.md
  shared/getting-started/getDeviceOnDash/artik5.md
  shared/getting-started/whatYouNeed/artik5.md
  shared/getting-started/whatYouNeed/kitra520.md
Labels: in progress, procbots/versionbot/ready-to-merge

#873 api-reference: Document 'is_active' device property
  CHANGELOG.md
  config/dictionaries/resource.json
  package.json
Labels: in progress, procbots/versionbot/ready-to-merge

#879 fix: Revert Procfile
  CHANGELOG.md
  Procfile
  package.json
  pages/reference/cli.md
  pages/reference/sdk/node-sdk.md
  pages/reference/sdk/python-sdk.md
Labels: in progress, procbots/versionbot/ready-to-merge

#864 base-images: Latest updates for base images documentation
  CHANGELOG.md
  Dockerfile
  package.json
  pages/reference/base-images/base-images.md
Labels: in progress, procbots/versionbot/ready-to-merge

#880 fix: Reduce use of parameterized names in base images docs
  CHANGELOG.md
  package.json
  pages/reference/base-images/base-images.md
Labels: in progress, procbots/versionbot/ready-to-merge

#881 Small fix
  pages/reference/base-images/base-images.md
Labels: in progress

#878 Merge into production
  CHANGELOG.md
  Dockerfile
  Procfile
  config/dictionaries/device.json
  config/dictionaries/resource.json
  package.json
  pages/reference/base-images/base-images.md
  pages/reference/cli.md
  pages/reference/sdk/node-sdk.md
  pages/reference/sdk/python-sdk.md
  shared/general/deviceTypeNames.md
  shared/getting-started/exampleProjects/artik5+nodejs.md
  shared/getting-started/exampleProjects/artik5+python.md
  shared/getting-started/getDeviceOnDash/artik5.md
  shared/getting-started/whatYouNeed/artik5.md
  shared/getting-started/whatYouNeed/kitra520.md
Labels: in progress, procbots/versionbot/no-checks

#852 Make it clear that the Intel NUC image supports generic x86 devices
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/faq/troubleshooting/faq.md
  shared/getting-started/introduction/intel-nuc.md
  static/img/intel-nuc/x86.png
Labels: in progress, procbots/versionbot/ready-to-merge

#885 ci: Switch to ResinCI
  .resinci.yml
  Makefile
  package.json
Labels: in progress
