Repository balena-io/docs, pull requests merged in 2018-03, with the labels that each got.

#731 Document masking NetworkManager in Changing the Network at Runtime
  CHANGELOG.md
  package.json
  shared/networking/2.x.md
Labels: procbots/versionbot/ready-to-merge

#734 Update app type info
  CHANGELOG.md
  package.json
  pages/learn/manage/app-types.md
Labels: in progress, procbots/versionbot/ready-to-merge

#735 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/manage/app-types.md
Labels: in progress, procbots/versionbot/no-checks

#736 Update app conversion info
  CHANGELOG.md
  package.json
  pages/learn/manage/app-types.md
Labels: in progress, procbots/versionbot/ready-to-merge

#740 Update redirect for build optimization page
  CHANGELOG.md
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/learn/deploy/build-optimization.md
Labels: in progress, procbots/versionbot/ready-to-merge

#737 Update persistent data info
  CHANGELOG.md
  package.json
  pages/learn/develop/multicontainer.md
  pages/reference/supervisor/docker-compose.md
Labels: in progress, procbots/versionbot/ready-to-merge

#743 Update build optimization redirects
  CHANGELOG.md
  config/redirects.txt
  package.json
  pages/learn/deploy/build-optimization.md
Labels: in progress, procbots/versionbot/ready-to-merge

#744 Deploy to production
  CHANGELOG.md
  config/redirects.txt
  package.json
  pages/learn/deploy/build-optimization.md
Labels: in progress, procbots/versionbot/no-checks

#745 Update config variables instructions for local mode
  CHANGELOG.md
  package.json
  pages/learn/develop/local-mode.md
  pages/learn/manage/configuration.md
  pages/learn/manage/serv-vars.md
  pages/reference/resinOS/advanced.md
Labels: in progress, procbots/versionbot/ready-to-merge

#746 Move warning for NUC about overwriting internal media
  CHANGELOG.md
  package.json
  shared/getDeviceOnDash/intel-nuc.md
Labels: in progress, procbots/versionbot/ready-to-merge

#747 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/develop/local-mode.md
  pages/learn/manage/configuration.md
  pages/learn/manage/serv-vars.md
  pages/reference/resinOS/advanced.md
  shared/getDeviceOnDash/intel-nuc.md
Labels: in progress, procbots/versionbot/no-checks

#751 Update missing links
  CHANGELOG.md
  package.json
  pages/learn/develop/dockerfile.md
  pages/learn/develop/hardware.md
  pages/learn/more/examples/seed-projects.md
  pages/learn/more/examples/snippets.md
Labels: in progress, procbots/versionbot/ready-to-merge

#755 Deploy to production
  CHANGELOG.md
  package.json
  pages/learn/develop/dockerfile.md
  pages/learn/develop/hardware.md
  pages/learn/more/examples/seed-projects.md
  pages/learn/more/examples/snippets.md
Labels: procbots/versionbot/no-checks

#754 Update ARTIK 5 and 10 to 520 and 1020 names
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/reference/base-images/resin-base-images.md
  pages/reference/data-api.md
  pages/reference/hardware/devices.md
  shared/exampleProjects/artik10+nodejs.md
  shared/exampleProjects/artik10+python.md
  shared/exampleProjects/artik5+nodejs.md
  shared/exampleProjects/artik5+python.md
  shared/general/resinDeviceTypeNames.md
  shared/whatYouNeed/artik10.md
  shared/whatYouNeed/artik5.md
Labels: in progress, procbots/versionbot/ready-to-merge

#756 Update redirects for queries and anchor links
  CHANGELOG.md
  config/redirects.txt
  package.json
  pages/learn/welcome/introduction.md
Labels: in progress, procbots/versionbot/ready-to-merge

#759 Deploy to production
  CHANGELOG.md
  config/dictionaries/device.json
  config/redirects.txt
  package.json
  pages/learn/welcome/introduction.md
  pages/reference/base-images/resin-base-images.md
  pages/reference/data-api.md
  pages/reference/hardware/devices.md
  shared/exampleProjects/artik10+nodejs.md
  shared/exampleProjects/artik10+python.md
  shared/exampleProjects/artik5+nodejs.md
  shared/exampleProjects/artik5+python.md
  shared/general/resinDeviceTypeNames.md
  shared/whatYouNeed/artik10.md
  shared/whatYouNeed/artik5.md
Labels: in progress, procbots/versionbot/no-checks

#760 Fix signup links in getting started guide
  CHANGELOG.md
  package.json
  pages/learn/getting-started.md
  shared/whatYouNeed/_default.md
  shared/whatYouNeed/hummingboard.md
  shared/whatYouNeed/imx6ul-var-dart.md
  shared/whatYouNeed/intel-nuc.md
  shared/whatYouNeed/jetson-tx2.md
  shared/whatYouNeed/nitrogen6x.md
  shared/whatYouNeed/raspberry-pi.md
  shared/whatYouNeed/raspberry-pi2.md
  shared/whatYouNeed/raspberrypi3.md
  shared/whatYouNeed/up-board.md
Labels: in progress, procbots/versionbot/ready-to-merge

#752 Update persistent storage info
  CHANGELOG.md
  package.json
  pages/faq/troubleshooting/faq.md
  pages/learn/develop/multicontainer.md
  pages/learn/manage/actions.md
  shared/general/persistent-storage.md
Labels: in progress, procbots/versionbot/ready-to-merge

#764 Fix note on purging data under move device action
  CHANGELOG.md
  package.json
  pages/learn/manage/actions.md
Labels: in progress

#765 Deploy to production
  CHANGELOG.md
  package.json
  pages/faq/troubleshooting/faq.md
  pages/learn/develop/multicontainer.md
  pages/learn/getting-started.md
  pages/learn/manage/actions.md
  shared/general/persistent-storage.md
  shared/whatYouNeed/_default.md
  shared/whatYouNeed/hummingboard.md
  shared/whatYouNeed/imx6ul-var-dart.md
  shared/whatYouNeed/intel-nuc.md
  shared/whatYouNeed/jetson-tx2.md
  shared/whatYouNeed/nitrogen6x.md
  shared/whatYouNeed/raspberry-pi.md
  shared/whatYouNeed/raspberry-pi2.md
  shared/whatYouNeed/raspberrypi3.md
  shared/whatYouNeed/up-board.md
Labels: in progress, procbots/versionbot/no-checks

#757 Update script for external pages
  CHANGELOG.md
  package.json
  pages/learn/deploy/release-strategy/update-locking.md
  pages/reference/cli.md
  pages/reference/sdk/python-sdk.md
  pages/reference/supervisor/supervisor-api.md
  tools/fetch-external.sh
Labels: in progress, procbots/versionbot/ready-to-merge

#762 Getting started guides for generic aarch64 and armv7
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/learn/getting-started.md
  shared/createAnApp/generic-aarch64.md
  shared/createAnApp/generic-armv7ahf.md
  shared/deployingCode/cpp.md
  shared/deployingCode/go.md
  shared/deployingCode/intel-nuc+nodejs.md
  shared/deployingCode/jetson-tx2+nodejs.md
  shared/deployingCode/nodejs.md
  shared/deployingCode/python.md
  shared/deployingCode/raspberrypi3+nodejs.md
  shared/deployingCode/rust.md
  shared/flashingOsToBootMedia/generic-aarch64.md
  shared/flashingOsToBootMedia/generic-armv7ahf.md
  shared/general/resinDeviceTypeNames.md
  shared/getDeviceOnDash/generic-aarch64.md
  shared/getDeviceOnDash/generic-armv7ahf.md
  shared/getResinOS/_default.md
  shared/getResinOS/generic-aarch64.md
  shared/getResinOS/generic-armv7ahf.md
  shared/networking/2.x.md
  shared/selectNetworkConfig/generic-aarch64.md
  shared/selectNetworkConfig/generic-armv7ahf.md
  shared/whatYouNeed/generic-aarch64.md
  shared/whatYouNeed/generic-armv7ahf.md
  static/img/device/generic-aarch64.svg
  static/img/device/generic-armv7ahf.svg
  static/img/generic-aarch64/app-type.png
  static/img/generic-aarch64/download_config.png
  static/img/generic-armv7ahf/app-type.png
  static/img/generic-armv7ahf/download_config.png
Labels: in progress, procbots/versionbot/ready-to-merge

#767 Deploy to production
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/learn/deploy/release-strategy/update-locking.md
  pages/learn/getting-started.md
  pages/reference/cli.md
  pages/reference/sdk/python-sdk.md
  pages/reference/supervisor/supervisor-api.md
  shared/createAnApp/generic-aarch64.md
  shared/createAnApp/generic-armv7ahf.md
  shared/deployingCode/cpp.md
  shared/deployingCode/go.md
  shared/deployingCode/intel-nuc+nodejs.md
  shared/deployingCode/jetson-tx2+nodejs.md
  shared/deployingCode/nodejs.md
  shared/deployingCode/python.md
  shared/deployingCode/raspberrypi3+nodejs.md
  shared/deployingCode/rust.md
  shared/flashingOsToBootMedia/generic-aarch64.md
  shared/flashingOsToBootMedia/generic-armv7ahf.md
  shared/general/resinDeviceTypeNames.md
  shared/getDeviceOnDash/generic-aarch64.md
  shared/getDeviceOnDash/generic-armv7ahf.md
  shared/getResinOS/_default.md
  shared/getResinOS/generic-aarch64.md
  shared/getResinOS/generic-armv7ahf.md
  shared/networking/2.x.md
  shared/selectNetworkConfig/generic-aarch64.md
  shared/selectNetworkConfig/generic-armv7ahf.md
  shared/whatYouNeed/generic-aarch64.md
  shared/whatYouNeed/generic-armv7ahf.md
  static/img/device/generic-aarch64.svg
  static/img/device/generic-armv7ahf.svg
  static/img/generic-aarch64/app-type.png
  static/img/generic-aarch64/download_config.png
  static/img/generic-armv7ahf/app-type.png
  static/img/generic-armv7ahf/download_config.png
  tools/fetch-external.sh
Labels: in progress
