Repository balena-io/docs, pull requests merged in 2018-07, with the labels that each got.

#839 Add information about application members
  CHANGELOG.md
  package.json
  pages/learn/manage/account.md
  static/img/common/app/add_member.png
  static/img/common/app/app_header.png
  static/img/common/app/member_dialog.png
  static/img/common/app/member_list.png
  static/img/common/app/members_tab.png
  static/img/common/app/remove_access.png
  static/img/common/app/shared_app.png
Labels: in progress, procbots/versionbot/ready-to-merge

#841 Deploy to production
  CHANGELOG.md
  config/dictionaries/device.json
  package.json
  pages/learn/deploy/release-strategy/update-locking.md
  pages/learn/manage/account.md
  pages/reference/cli.md
  pages/reference/sdk/node-sdk.md
  pages/reference/sdk/python-sdk.md
  pages/reference/supervisor/supervisor-api.md
  shared/getDeviceOnDash/artik533s.md
  shared/whatYouNeed/artik530.md
  shared/whatYouNeed/artik533s.md
  static/img/artik533s/add-device.png
  static/img/artik533s/app-type.png
  static/img/artik533s/artik533s.jpg
  static/img/artik533s/os-options.png
  static/img/common/app/add_member.png
  static/img/common/app/app_header.png
  static/img/common/app/member_dialog.png
  static/img/common/app/member_list.png
  static/img/common/app/members_tab.png
  static/img/common/app/remove_access.png
  static/img/common/app/shared_app.png
  static/img/device/artik533.svg
Labels: in progress, procbots/versionbot/no-checks

#842 New page for billing
  CHANGELOG.md
  config/navigation.txt
  package.json
  pages/learn/manage/billing.md
  static/img/common/billing/account_details.png
  static/img/common/billing/sub_sum.png
  static/img/common/billing/usage.png
  ~
Labels: in progress, procbots/versionbot/ready-to-merge

#844 Deploy to production
  CHANGELOG.md
  config/navigation.txt
  package.json
  pages/learn/manage/billing.md
  static/img/common/billing/account_details.png
  static/img/common/billing/sub_sum.png
  static/img/common/billing/usage.png
  ~
Labels: in progress, procbots/versionbot/no-checks

#726 Update 2.x.md
  shared/networking/2.x.md
Labels: in progress

#822 Inserted missing "\"
  pages/learn/develop/runtime.md
Labels: in progress

#826 Update dockerfile.md
  pages/learn/develop/dockerfile.md
Labels: in progress

#827 Fix simple typo
  pages/learn/develop/dockerfile.md
Labels: in progress

#850 Update supported cellular modem list
  CHANGELOG.md
  package.json
  shared/network/2.x.md
Labels: in progress, procbots/versionbot/ready-to-merge

#851 Deploy to production
  CHANGELOG.md
  package.json
  shared/network/2.x.md
Labels: in progress, procbots/versionbot/no-checks

#853 docs: mention folder of 'persistentlogging' logs
  CHANGELOG.md
  package.json
  pages/reference/cli.md
  pages/reference/sdk/node-sdk.md
  shared/overview/2.x.md
Labels: in progress, procbots/versionbot/ready-to-merge

#855 fix: Update navigation to reflect new base image page name
  CHANGELOG.md
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/faq/troubleshooting/faq.md
Labels: in progress, procbots/versionbot/ready-to-merge

#857 Deploy to production
  CHANGELOG.md
  config/navigation.txt
  config/redirects.txt
  package.json
  pages/faq/troubleshooting/faq.md
Labels: in progress

#858 fix: Improve navigation headers for dynamic pages.
  CHANGELOG.md
  config/navigation.txt
  package.json
Labels: in progress, procbots/versionbot/ready-to-merge
