Repository balena-io/docs, pull requests merged in 2021-03, with the labels that each got.

#1664 update-process: Document that not all files in boot are updated
  pages/reference/OS/updates/update-process.md
Labels: docs/meta

#1672 wifi-dongles: update list
  pages/reference/hardware/wifi-dongles.md
Labels: balenaCoins: 10

#1679 Update language stack available and latest versions
  pages/reference/base-images/base-images.md
Labels: balenaCoins: 10

#1681 Disable the note about disabling deltas
  pages/learn/deploy/delta.md
Labels: balenaCoins: 10

#1691 Improve build optimization instructions
  pages/learn/deploy/build-optimization.md
Labels: balenaCoins: 30

#1700 Parallelize external docs fetching, dropping from 8s to 3s locally
  tools/fetch-external.sh
Labels: balenaCoins: 30

#1693 Clarify the depends_on behavior in multicontainer apps
  pages/learn/develop/multicontainer.md
Labels: balenaCoins: 10

#1702 Fix broken link for contributing to CLI docs
  config/links.coffee
Labels: balenaCoins: 10

#1697 Removed typo
  pages/learn/welcome/introduction.md
Labels: balenaCoins: 10

#1696 Pin the base image to nodejs 14 LTS
  Dockerfile
  package.json
Labels: balenaCoins: 10

#1690 Add a periodic GitHub action to scan markdown files for broken hyperlinks
  .github/workflows/link-checker.yml
Labels: balenaCoins: 70

#1715 Changing app types when upgrading plan
  pages/learn/manage/app-types.md
Labels: balenaCoins: 10

#1669 deltas: fix links on deltas page
  pages/learn/deploy/delta.md
Labels: balenaCoins: 10

#1688 Fix typos
  pages/learn/develop/dockerfile.md
  pages/learn/develop/local-mode.md
  pages/learn/develop/multicontainer.md
  shared/general/labels.md
  shared/getting-started/getDeviceOnDash/intel-edison.md
  shared/getting-started/getDeviceOnDash/ts4900.md
Labels: balenaCoins: 10

#1730 Remove old resin dashboard screenshot
  shared/getting-started/getDeviceOnDash/beaglebone-black.md
Labels: balenaCoins: 10

#1708 Clarifying wording about language stacks
  pages/reference/base-images/base-images.md
Labels: balenaCoins: 30

#1685 Added note that inactive devices count against starter application limit
  pages/learn/manage/app-types.md
Labels: balenaCoins: 10

#1753 Edit grammar errors in build optimization
  pages/learn/deploy/build-optimization.md
Labels: balenaCoins: 10

#1755 Adding wifi context to applicable devices
  shared/getting-started/getDeviceOnDash/_default.md
  shared/getting-started/getDeviceOnDash/asus-tinker-board.md
  shared/getting-started/getDeviceOnDash/jetson-nano.md
  shared/getting-started/getDeviceOnDash/raspberry-pi.md
  shared/getting-started/getDeviceOnDash/raspberry-pi2.md
  shared/getting-started/getDeviceOnDash/raspberrypi3-64.md
  shared/getting-started/getDeviceOnDash/raspberrypi3.md
  shared/getting-started/getDeviceOnDash/raspberrypi4-64.md
Labels: balenaCoins: 10

#1761 Fix balena_restart_device typo
  pages/learn/develop/runtime.md
Labels: balenaCoins: 10

#1759 Fix project demo URL
  pages/learn/more/examples/projects.md
Labels: balenaCoins: 10

#1763 Fix typos and improve clarity
  pages/learn/deploy/offline-updates.md
Labels: balenaCoins: 10

#1661 Password for social login
  pages/learn/manage/account.md
Labels: balenaCoins: 10

#1721 Update the device statuses
  pages/learn/manage/device-statuses.md
  static/img/common/main_dashboard/device_status.png
Labels: balenaCoins: 30

#1718 Document maximum env/service/app variable value size
  pages/learn/manage/serv-vars.md
Labels: balenaCoins: 10

#1689 Correct supported devices list links fixes #1682
  shared/getting-started/whatYouNeed/asus-tinker-board-s.md
  shared/getting-started/whatYouNeed/asus-tinker-board.md
Labels: balenaCoins: 10

#1762 Fixed broken project link for nodejs picamera
  pages/learn/more/examples/snippets.md
Labels: balenaCoins: 10

#1713 Updated ESR List
  pages/reference/OS/extended-support-release.md
Labels: balenaCoins: 10

#1684 Add getting started for NanoPi Neo Air fixes #1647
  config/dictionaries/device.json
  shared/getting-started/whatYouNeed/nanopi-neo-air.md
  static/img/getting-started/application/nanopi-neo-air.png
  static/img/getting-started/create-application/nanopi-neo-air.png
  static/img/getting-started/devices/nanopi-neo-air.png
  static/img/nanopi-neo-air/nanopi-neo-air.jpg
Labels: balenaCoins: 10

#1668 Adding genericX86_64 to the device types to try
  pages/faq/troubleshooting/faq.md
Labels: balenaCoins: 10

#1704 add matrix to the member types
  pages/learn/manage/account.md
Labels: balenaCoins: 10

#1714 Specify File Location for NM
  shared/network/2.x.md
Labels: balenaCoins: 10
