Repository balena-io/docs, pull requests merged in 2023-04, with the labels that each got.

#2671 Add ClearBlade-GCP selection to cloud IoT provisioning page
  config/dictionaries/cloud.json
  pages/learn/develop/cloud-iot-provisioning.md
Labels: scope/enhancement, learn/develop

#2678 Deployment: Update screenshots
  pages/learn/deploy/deployment.md
  static/img/common/app/release_filter.png
  static/img/common/app/release_list.png
  static/img/common/app/release_summary.png
  static/img/common/deployment/git-remote.png
Labels: scope/enhancement

#2676 Update Local Mode docs phrasing and screenshots
  pages/learn/develop/local-mode.md
  static/img/local-mode/device-in-local-mode-20-01-09.png
  static/img/local-mode/device-in-local-mode.png
Labels: scope/enhancement

#2677 Blocks: Update hub image and text
  pages/learn/develop/blocks.md
  static/img/blocks/image-ref.png
  static/img/blocks/use-button.png
Labels: scope/enhancement

#2679 Release Policy: Update docs and screenshots
  pages/learn/deploy/release-strategy/release-policy.md
  static/img/common/release-policy/HKAHHmS.png
  static/img/common/release-policy/SCESUYd.png
  static/img/common/release-policy/T3Jy5l1.png
  static/img/common/release-policy/device_settings.png
  static/img/common/release-policy/device_target_release_pencil.png
  static/img/common/release-policy/devices_table_modify.png
  static/img/common/release-policy/mNCaLF8.gif
  static/img/common/release-policy/obsIjdo.png
  static/img/common/release-policy/pin_to_release_setting.png
  static/img/common/release-policy/rdKoNe9.png
  static/img/common/release-policy/releases_card_dropdown.png
  static/img/common/release-policy/target_release_pin.png
Labels: scope/enhancement

#2687 Release policy: Fix target release pencil image not working
  pages/learn/deploy/release-strategy/release-policy.md
Labels: scope/bug
